#!/usr/bin/env python3
"""create_config.py — 策略运行时配置生成 (Phase 4)"""

import argparse, json, os, sys
from datetime import datetime
from pathlib import Path

def _parse_yaml(path: str) -> dict:
    try: import yaml; return yaml.safe_load(open(path)) or {}
    except ImportError: return {}

def generate_runtime_config(strategy_dir: str, symbols: list = None,
                            capital: int = 10000, leverage: int = 1,
                            max_positions: int = 3, position_size_pct: float = 0.1,
                            ws_url: str = "wss://stream.binance.com:9443/ws",
                            rest_url: str = "https://api.binance.com") -> dict:
    sdir = Path(strategy_dir)
    name = sdir.name

    config_path = None
    for cn in ["config.test.yaml", "config.yaml"]:
        if (sdir / cn).is_file(): config_path = str(sdir / cn); break
    if not config_path:
        cd = sdir / "config"
        if cd.is_dir():
            for c in sorted(cd.glob("*.yaml")): config_path = str(c); break

    base_cfg = {}
    if config_path:
        data = _parse_yaml(config_path)
        sc = data.get(name, data)
        if isinstance(sc, dict): base_cfg = sc

    sym = symbols or base_cfg.get("symbols", [])
    if isinstance(sym, str): sym = [s.strip() for s in sym.split(',')]

    tf = base_cfg.get("timeframes", ["1h"])
    if isinstance(tf, str): tf = [t.strip() for t in tf.split(',')]

    return {
        name: {
            "enabled": True,
            "symbols": sym,
            "timeframes": tf,
            "direction": base_cfg.get("direction", "neutral"),
            "params": base_cfg.get("params", {}),
        },
        "runtime": {
            "generated_at": datetime.now().isoformat(),
            "source_config": config_path,
            "capital": capital,
            "leverage": leverage,
            "max_positions": max_positions,
            "position_size_pct": position_size_pct,
            "stop_loss_pct": 0.05,
            "take_profit_pct": 0.15,
            "websocket_url": ws_url,
            "rest_url": rest_url,
            "log_level": "INFO",
            "log_dir": "./logs",
        }
    }

def format_yaml(data: dict) -> str:
    lines = ["# Runtime config — generated by create_config.py",
             f"# {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ""]
    def _emit(d, indent=0):
        pre = "  " * indent
        for k, v in d.items():
            if isinstance(v, dict):
                lines.append(f"{pre}{k}:")
                _emit(v, indent + 1)
            elif isinstance(v, list):
                lines.append(f"{pre}{k}:")
                for item in v: lines.append(f"{pre}  - {item}")
            elif isinstance(v, bool):
                lines.append(f"{pre}{k}: {'true' if v else 'false'}")
            elif isinstance(v, str):
                lines.append(f"{pre}{k}: {v}")
            else:
                lines.append(f"{pre}{k}: {v}")
    _emit(data)
    return '\n'.join(lines)

def main():
    p = argparse.ArgumentParser(description="Generate runtime strategy config")
    p.add_argument("--strategy-dir", required=True)
    p.add_argument("--symbols", default="")
    p.add_argument("--output", default="")
    p.add_argument("--capital", type=int, default=10000)
    p.add_argument("--leverage", type=int, default=1)
    p.add_argument("--max-positions", type=int, default=3)
    p.add_argument("--position-size-pct", type=float, default=0.1)
    p.add_argument("--ws-url", default="wss://stream.binance.com:9443/ws")
    p.add_argument("--rest-url", default="https://api.binance.com")
    p.add_argument("--json", action="store_true")
    args = p.parse_args()

    capital = int(os.environ.get("DEFAULT_CAPITAL", args.capital))
    leverage = int(os.environ.get("DEFAULT_LEVERAGE", args.leverage))
    max_pos = int(os.environ.get("MAX_POSITIONS", args.max_positions))
    pos_pct = float(os.environ.get("POSITION_SIZE_PCT", args.position_size_pct))

    syms = [s.strip() for s in args.symbols.split(',')] if args.symbols else None

    cfg = generate_runtime_config(args.strategy_dir, syms, capital, leverage, max_pos, pos_pct,
                                  args.ws_url, args.rest_url)

    if args.json:
        print(json.dumps(cfg, indent=2, ensure_ascii=False))
    else:
        yaml_str = format_yaml(cfg)
        if args.output:
            os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
            with open(args.output, 'w') as f: f.write(yaml_str)
            print(f"Config written to: {args.output}")
            print(f"\n{yaml_str}")
        else:
            print(yaml_str)

    return 0

if __name__ == "__main__": sys.exit(main())
