product:
  strategy_name1:
    host: 127.0.0.1
    path: /home/qpw/workspace/{strategy_name}
  strategy_name2:
    host: 127.0.0.1
    path: /home/qpw/workspace/{strategy_name}

paper:
  strategy_name2:
    host: 127.0.0.1
    path: /home/qpw/workspace/{strategy_name}
  strategy_name3:
    host: 127.0.0.1
    path: /home/qpw/workspace/{strategy_name}

smoking:
  strategy_name4:
    host: 127.0.0.1
    path: /home/qpw/workspace/{strategy_name}
  strategy_name5:
    host: 127.0.0.1
    path: /home/qpw/workspace/{strategy_name}
  